check-updates: true
replant-chance: 90

replant:
  oak_sapling: true
  birch_sapling: true
  spruce_sapling: true
  jungle_sapling: true
  acacia_sapling: true
  dark_oak_sapling: true
  mangrove_propagule: true
  bamboo_sapling: true
  bamboo: true
  sugar_cane: true
  cactus: true
  dandelion: true
  poppy: true
  blue_orchid: true
  allium: true
  red_tulip: true
  orange_tulip: true
  white_tulip: true
  pink_tulip: true
  oxeye_daisy: true
  cornflower: true
  lily_of_the_valley: true
  wither_rose: true
  sunflower: true
  lilac: true
  rose_bush: true
  peony: true
  fern: true
  large_fern: true
  short_grass: true
  tall_grass: true
  red_mushroom: true
  brown_mushroom: true
  crimson_fungus: true
  warped_fungus: true
  crimson_roots: true
  warped_roots: true
  dead_brain_coral_fan: true
  dead_bubble_coral_fan: true
  dead_fire_coral_fan: true
  dead_horn_coral_fan: true
  dead_tube_coral_fan: true
  wheat_seeds: true
  beetroot_seeds: true
  potato: true
  carrot: true
  pumpkin_seeds: true
  melon_seeds: true
  sweet_berries: true
