name: RealisticGrowth
version: '${project.version}'
website: https://github.com/cyklon73
main: de.cyklon.realisticgrowth.RealisticGrowth
api-version: 1.21

permissions:
  rg.update:
    description: Receives update messages and can run updates
    default: op

commands:
  realistic-growth:
    description: manage the plugin
    permission: rg.update
    aliases: rg
    usage: "§cUsage: /realistic-growth update"